services:
  rabbitmq:
    image: rabbitmq:alpine
    container_name: rabbitmq
    ports:
      - "40247:5672" # Port dla komunikacji RabbitMQ
      - "40248:15672" # Port dla panelu zarządzania RabbitMQ

  product:
    build:
      context: ./product
    container_name: product
    ports:
      - "8002:8002"
    restart: always
    depends_on:
      - "rabbitmq"
    volumes:
      - ./product:/app
    env_file:
      - ./product/.env.dev

  shopping:
    build:
      context: ./shopping
    container_name: shopping
    ports:
      - "8003:8003"
    restart: always
    depends_on:
      - "rabbitmq"
    volumes:
      - ./shopping:/app
    env_file:
      - ./shopping/.env.dev

  customer:
    build:
      context: ./customer
    container_name: customer
    ports:
      - "8001:8001"
    restart: always
    depends_on:
      - "rabbitmq"
    volumes:
      - ./customer:/app
    env_file:
      - ./customer/.env.dev

  nginx-proxy:
    build:
      context: ./proxy
    depends_on:
      - product
      - shopping
      - customer
    ports:
      - "80:80"

networks:
  default:
    name: shopping_ms_default
